---
- name: Install PostgreSQL packages for Debian
  apt: name={{ item }} state=latest
  loop:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL packages for RHEL
  yum: name={{ item }} state=latest
  loop:
    - postgresql
    - postgresql-server
    - python3-psycopg2 
  when: ansible_os_family == "RedHat"