---
- name: Install NGINX for Debian
  apt:
    name: nginx
    state: latest
  when: ansible_os_family == "Debian"

- name: Install NGINX for RHEL
  yum:
    name: nginx
    state: latest
  when: ansible_os_family == "Redhat"