apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomcat-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /sample
        pathType: ImplementationSpecific
        backend:
          service
            name: tomcat-service
            port:
              number: 80
