---
- name: Required sys packages for Debian
  apt: pkg={{ item }}
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
  when: ansible_os_family == "Debian"

- name: Required sys packages for RHEL
  yum: name={{ item }} state=latest update_cache=true
  loop:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  when: ansible_os_family == "RedHat"