---
- name: Allow md5 connection for the db user
  vars:
    - include_vars: "../vars/main.yml"
  postgresql_pg_hba:
    dest: ~/data/pg_hba.conf
    contype: host
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become: yes
  become_user: postgres
  notify: restart postgres