---
- name: Install packages
  import_tasks: req_pkgs.yml

- name: PostgreSQL Initialization for Debian
  import_tasks: pgsql_init_deb.yml
  when: ansible_os_family=="Debian"

- name: PostgreSQL Initialization for RHEL
  import_tasks: pgsql_init_rhel.yml
  when: ansible_os_family=="RedHat"
  
- name: Ensure PostgreSQL is enabled and running
  import_tasks: service.yml

- name: Create app database
  import_tasks: create_db.yml

- name: Create db user
  import_tasks: create_dbuser.yml

- name: Grant db user access
  import_tasks: grant_dbaccess.yml

- name: Allow md5 connection for the db user
  import_tasks: allow_md5.yml