---
- name: Install PostgreSQL packages for Debian
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: latest
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL packages for RHEL
  yum:
    name:
      - postgresql
      - postgresql-server
      - python3-psycopg2
    state: latest
  when: ansible_os_family == "RedHat"