---
- name: Verify NGINX installation on servers
  hosts: servers
  become: true

  vars:
    http_port: 80
    server_ip: 192.168.1.100
    server_port: 8000
    nginx_server_name: example.com

  tasks:
    - name: Install NGINX on CentOS
      yum:
        name: nginx
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install NGINX on Ubuntu
      apt:
        name: nginx
        state: latest
      when: ansible_os_family == "Debian"

    - name: Write the NGINX config file
      template:
        src: ../srv/nginx.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
      notify:
        - Restart NGINX

    - name: Ensure NGINX is enabled and running
      service:
        name: nginx
        enabled: yes
        state: started

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted 
