---
- name: Docker repo for Debian
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: latest
  when: ansible_os_family == "Debian"

- name: Docker repo for RHEL
  yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/centos/gpg"
  when: ansible_os_family == "Redhat"